apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dividend-tracker-mongodb-pvc
  namespace: default
  labels:
    app: dividend-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
